# MQTT Broker Config
MQTT_HOST = "192.168.0.0"
MQTT_PORT = 8883
MQTT_USERNAME = "user"
MQTT_PASSWORD = "pwd"
MQTT_CACERT = r"ca.crt"
MQTT_TLSVERSION = 5     # PROTOCOL_TLSv1_2 = 5
MQTT_CLIENTID = "name"
MQTT_CERT = None
MQTT_KEY = None

# InfluxDb Config
INFLUXDB_HOST = '192.168.0.1'
INFLUXDB_PORT = '8086'
INFLUXDB_USER = 'user'
INFLUXDB_PWD = 'pwd'
INFLUXDB_DATABASE = 'db'
INFLUXDB_MEASUREMENT = 'm'
