# MQTT Broker Config
MQTT_HOST = "ip"
MQTT_PORT = 8883
MQTT_USERNAME = "user"
MQTT_PASSWORD = "pwd"
MQTT_CACERT = "path"
MQTT_TLSVERSION = 5     # PROTOCOL_TLSv1_2 = 5
MQTT_CLIENTID = "name"
MQTT_CERT = None
MQTT_KEY = None